# Generated by Django 5.0 on 2024-01-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appoinment_time'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoinment',
            name='patient',
        ),
        migrations.AddField(
            model_name='appoinment',
            name='patient',
            field=models.ManyToManyField(to='patient.patient'),
        ),
    ]
